dataset: celeba
dataset_type: image
batch_size: 64
noise_type: privacy
noise_level: 0.1
model: mobilenet
model_path: mobilenet_model.pth
learning_rate: 0.001
num_classes: 40
num_epochs: 10
loss_function: bce_with_logits
#loss_function: cross_entropy
target_float: True
multi_targets: True
#privacy_function: gaussian
#privacy_function: add_optimized_tensor_noise_Yang
privacy_function: rrldp_gaussian
epsilon: 10
sensitivity: 2