dataset: cifar10
dataset_type: image
batch_size: 64
#noise_type: none
noise_type: privacy
noise_level: 0.1
model: mobilenet
model_path: mobilenet_model.pth
learning_rate: 0.001
num_classes: 10
num_epochs: 10
loss_function: cross_entropy
#privacy_function: perturb_tensor_krr
#privacy_function: laplace
#privacy_function: gaussian
#privacy_function: add_optimized_tensor_noise_Yang
privacy_function: rrldp_laplace
#privacy_function: rrldp_gaussian
#privacy_function: mvg_mechanism
#privacy_function: perturb_tensor_adaptive_iterative
#privacy_function: adaptive_clipping_weight_perturb
#privacy_function: add_weighted_noise_rrldp_laplace
#privacy_function: add_weighted_noise_rrldp_gaussian
epsilon: 0.3
sensitivity: 2
target_float: False
multi_targets: False